#!/usr/bin/env python3
"""Validate a DualVLN evidence annotation JSONL without changing the source file."""
from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path


NEED = {"yes", "no", "uncertain"}
ROLE = {"localization", "direction", "landmark", "revisit", "safety", "none", "uncertain"}
CONFIDENCE = {"high", "medium", "low"}
LABELS = {"A", "B", "C"}
SPECIAL = {"none", "uncertain"}


def read_jsonl(path: Path):
    rows = []
    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            rows.append((line_no, json.loads(line)))
        except json.JSONDecodeError as exc:
            raise ValueError(f"第 {line_no} 行不是有效 JSON: {exc}") from exc
    return rows


def canonical(row):
    """Fields generated by the miner; annotation metadata is deliberately excluded."""
    return {k: v for k, v in row.items() if k not in {"annotation", "annotator_id", "created_at"}}


def digest(value):
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def validate_row(row, line_no, base_dir):
    errors, warnings = [], []
    prefix = f"第 {line_no} 行"
    if row.get("schema_version") != 1:
        errors.append(f"{prefix}: schema_version 不是 1")
    if not row.get("annotation_id"):
        errors.append(f"{prefix}: 缺少 annotation_id")
    candidates = row.get("candidates") or []
    labels = {c.get("label") for c in candidates}
    if not labels.issubset(LABELS) or len(labels) != len(candidates):
        errors.append(f"{prefix}: 候选标签重复或不是 A/B/C")
    current = row.get("current_frame_id")
    for c in candidates:
        if not isinstance(c.get("frame_id"), int) or not isinstance(current, int) or c["frame_id"] >= current:
            errors.append(f"{prefix}: 存在非因果历史 frame_id")
        if c.get("age") != current - c.get("frame_id"):
            errors.append(f"{prefix}: age 与 frame_id 不一致")
        if base_dir and c.get("image_path") and not (base_dir / c["image_path"]).is_file():
            errors.append(f"{prefix}: 缺失历史图像 {c['image_path']}")
    if base_dir and row.get("current_image_path") and not (base_dir / row["current_image_path"]).is_file():
        errors.append(f"{prefix}: 缺失当前图像 {row['current_image_path']}")
    causal = row.get("causal_check") or {}
    if causal.get("all_history_before_current") is not True or causal.get("future_input_exposed") is not False:
        errors.append(f"{prefix}: causal_check 未通过")
    ann = row.get("annotation") or {}
    need, role, confidence = ann.get("need_history"), ann.get("evidence_role"), ann.get("confidence")
    preferred, misleading = ann.get("preferred_evidence"), ann.get("misleading_evidence")
    if need not in NEED:
        errors.append(f"{prefix}: need_history 枚举无效")
    if role not in ROLE:
        errors.append(f"{prefix}: evidence_role 枚举无效")
    if confidence not in CONFIDENCE:
        errors.append(f"{prefix}: confidence 枚举无效")
    for name, values, max_count in (("preferred_evidence", preferred, 2), ("misleading_evidence", misleading, 3)):
        if not isinstance(values, list) or not values or len(values) > max_count:
            errors.append(f"{prefix}: {name} 必须是 1--{max_count} 项列表")
            continue
        if len(values) != len(set(values)) or not set(values).issubset(labels | SPECIAL):
            errors.append(f"{prefix}: {name} 含无效、重复或不存在的标签")
        if SPECIAL.intersection(values) and (len(values) != 1 or values[0] not in SPECIAL):
            errors.append(f"{prefix}: {name} 的 none/uncertain 必须单独出现")
    if need == "no" and preferred != ["none"]:
        errors.append(f"{prefix}: need_history=no 时 preferred_evidence 必须为 none")
    if need == "uncertain" and preferred != ["uncertain"]:
        errors.append(f"{prefix}: need_history=uncertain 时 preferred_evidence 必须为 uncertain")
    if need == "yes" and (not isinstance(preferred, list) or not any(x in labels for x in preferred)):
        errors.append(f"{prefix}: need_history=yes 时至少选择一个 A/B/C")
    if need == "no" and role != "none":
        errors.append(f"{prefix}: need_history=no 时 evidence_role 应为 none")
    if need == "uncertain" and role != "uncertain":
        errors.append(f"{prefix}: need_history=uncertain 时 evidence_role 应为 uncertain")
    if ann.get("short_reason", "") and len(ann["short_reason"]) > 30:
        warnings.append(f"{prefix}: short_reason 超过 30 字")
    if not row.get("annotator_id"):
        errors.append(f"{prefix}: 缺少 annotator_id")
    return errors, warnings


def compare_manifest(rows, manifest_path):
    if not manifest_path:
        return [], {"checked": False, "mismatches": 0}
    manifest = {row.get("annotation_id"): row for _, row in read_jsonl(manifest_path)}
    errors = []
    for line_no, row in rows:
        base = manifest.get(row.get("annotation_id"))
        if base is None:
            errors.append(f"第 {line_no} 行: annotation_id 不在 candidate_manifest")
        # Compare parsed structures so JSON's harmless 1 vs 1.0 formatting
        # difference does not look like user tampering.
        elif canonical(base) != canonical(row):
            errors.append(f"第 {line_no} 行: 程序生成字段与 candidate_manifest 漂移")
    return errors, {"checked": True, "manifest_rows": len(manifest), "mismatches": len(errors)}


def make_svg(metrics, path):
    bars = [("通过", metrics["valid_rows"], "#2f855a"), ("错误", metrics["error_count"], "#c53030"), ("警告", metrics["warning_count"], "#b7791f")]
    maximum = max(1, *(x[1] for x in bars))
    items = []
    for i, (label, value, color) in enumerate(bars):
        y = 70 + i * 42
        width = 410 * value / maximum
        items.append(f'<text x="24" y="{y+17}" font-size="15">{label}</text><rect x="86" y="{y}" width="410" height="23" fill="#edf2f7"/><rect x="86" y="{y}" width="{width:.1f}" height="23" fill="{color}"/><text x="510" y="{y+17}" font-size="15">{value}</text>')
    path.write_text('<svg xmlns="http://www.w3.org/2000/svg" width="590" height="220"><rect width="100%" height="100%" fill="white"/><text x="24" y="32" font-size="21" font-weight="700">DualVLN 标注校验</text>' + ''.join(items) + '</svg>\n', encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="校验 DualVLN 人工证据标注 JSONL")
    ap.add_argument("--annotations", required=True, type=Path)
    ap.add_argument("--manifest", type=Path)
    ap.add_argument("--base-dir", type=Path, help="相对 image_path 的根目录")
    ap.add_argument("--output-dir", required=True, type=Path)
    args = ap.parse_args()
    rows = read_jsonl(args.annotations)
    errors, warnings = [], []
    seen = set()
    for line_no, row in rows:
        if row.get("annotation_id") in seen:
            errors.append(f"第 {line_no} 行: annotation_id 重复")
        seen.add(row.get("annotation_id"))
        e, w = validate_row(row, line_no, args.base_dir)
        errors.extend(e); warnings.extend(w)
    manifest_errors, manifest_metrics = compare_manifest(rows, args.manifest)
    errors.extend(manifest_errors)
    ann_counter = Counter((r.get("annotation") or {}).get("need_history") for _, r in rows)
    metrics = {"schema_version": 1, "status": "passed" if not errors else "failed", "annotation_file": str(args.annotations), "row_count": len(rows), "unique_annotation_ids": len(seen), "valid_rows": len(rows) if not errors else max(0, len(rows) - len({e.split(':')[0] for e in errors})), "error_count": len(errors), "warning_count": len(warnings), "need_history": dict(ann_counter), "manifest": manifest_metrics, "errors": errors[:100], "warnings": warnings[:100]}
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "metrics.json").write_text(json.dumps(metrics, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    status = "通过" if metrics["status"] == "passed" else "失败"
    summary = f"""# DualVLN 人工标注校验

- 状态：**{status}**
- 记录数：{len(rows)}；唯一 annotation_id：{len(seen)}
- 错误：{len(errors)}；警告：{len(warnings)}
- need_history：`{dict(ann_counter)}`
- 模板漂移检查：{'已执行' if manifest_metrics['checked'] else '未提供 manifest'}

## 结果分析

{('所有结构、枚举、因果字段、图像路径和模板字段均通过校验，可以进入只读 relevance probe。' if not errors else '存在结构或模板错误，不能把该文件接入训练；请先查看 metrics.json 中的 errors。')}

校验脚本不会修改人工原始 JSONL。
"""
    (args.output_dir / "summary.md").write_text(summary, encoding="utf-8")
    make_svg(metrics, args.output_dir / "metrics.svg")
    (args.output_dir / "errors.log").write_text("\n".join(errors + warnings) + ("\n" if errors or warnings else ""), encoding="utf-8")
    print(f"状态: {status} | 记录: {len(rows)} | 错误: {len(errors)} | 警告: {len(warnings)}")
    print(f"need_history: {dict(ann_counter)}")
    print(f"报告目录: {args.output_dir}")
    return 0 if not errors else 1


if __name__ == "__main__":
    raise SystemExit(main())
